### ISSUE TITLE
Fresh Intellivent SKY

### ISSUE THREAD

**Issue by skynetforcats** [PatrickE94/pycalima#21]
Just saw this in the local store: https://intelliventsky.com/ 
It even has an "air quality sensor that is able to detect strong odours" 😅
I tried downloading teir app and it looks almost identical to the Pax Calima app except for the brand, colors and version number. So I assume pycalima would work with very little adjustments.
Not that I'm going to replace the Calima for now but just thought it was an interesting find.

**Comment by BjornPoppe** [comment]
Fresh is in the same corporate group as Pax...
